Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "test/**/*.rb"
    - "**/Vagrantfile"
    - "Vagrantfile.template.rb"
Naming/FileName:
  Exclude:
    - "Vagrantfile.template.rb"
Style/FrozenStringLiteralComment:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets
AllCops:
  NewCops: enable
