# -*- mode: ruby -*-
# vi: set ft=ruby :

required_plugins = {
  'vagrant-reload' => {
    'version' => '>= 0.0.1'
  }
}

Vagrant.configure('2') do |config|
  config.vagrant.plugins = required_plugins
  config.vm.box = 'AntonioMeireles/CLearLinux'
  config.vm.define 'gnome-desktop'
  config.vm.hostname = 'gnome.clearlinux.local'
  %w[vmware_fusion vmware_desktop vmware_workstation].each do |provider|
    config.vm.provider provider do |vmware|
      vmware.gui = true
      {
        'memsize' => 8192,
        'numvcpus' => 4
      }.each { |k, v| vmware.vmx[k.to_s] = v.to_s }
    end
  end
  config.vm.provider 'virtualbox' do |vbox|
    vbox.gui = true
    {
      '--memory' => 8192,
      '--cpus' => 4
    }.each { |k, v| vbox.customize ['modifyvm', :id, k.to_s, v.to_s] }
  end

  config.vm.provision :bundle_add, bundles: ['desktop-autostart']
  config.vm.provision :reload
end
