Vagrant.configure('2') do |config|
  config.vm.box = 'clear-test'
  config.vm.define 'test-box'
  config.vm.hostname = 'test.clearlinux.local'
  config.vm.provider :libvirt do |libvirt, override|
    host = 'libvirt-host.clearlinux.local'
    username = 'clear'
    libvirt.host = host
    libvirt.connect_via_ssh = true
    libvirt.username = username
    libvirt.socket = '/var/run/libvirt/libvirt-sock'
    libvirt.storage_pool_path = '/home/clear/.local/share/libvirt/images'
    libvirt.loader = '/usr/share/qemu/OVMF.fd'
    override.ssh.forward_agent = true
    override.ssh.proxy_command = "ssh -q -W %h:%p -l #{username} -x #{host}"
  end
end
