Vagrant.configure('2') do |config|
  config.vm.box = 'clear-test'
  config.vm.define 'test-box'
  config.vm.hostname = 'test.clearlinux.local'
  config.vm.provider :libvirt do |libvirt, _override|
    libvirt.host = 'libvirt-host.clearlinux.local'
    libvirt.connect_via_ssh = true
    libvirt.username = 'clear'
    libvirt.socket = '/var/run/libvirt/libvirt-sock'
    libvirt.storage_pool_path = '/home/clear/.local/share/libvirt/images'
    libvirt.loader = '/usr/share/qemu/OVMF.fd'
    config.ssh.forward_agent = true
    config.ssh.proxy_command =
      "ssh -q -W %h:%p -l #{libvirt.username} -x #{libvirt.host}"
  end
end
