required_plugins = {
  'vagrant-hostsupdater' => {
    'version' => '>= 1.1.1.160'
  },
  'vagrant-reload' => {
    'version' => '>= 0.0.1'
  },
  'vagrant-guests-clearlinux' => {
    'version' => '>= 1.2.2'
  }
}

VMWARE = %w[vmware_fusion vmware_desktop vmware_workstation].freeze

Vagrant.configure(2) do |config|
  config.vagrant.plugins = required_plugins
  config.vm.define :libvirt
  config.vm.hostname = 'libvirt-host.clearlinux.local'
  config.vm.box = 'AntonioMeireles/clearlinux'
  # check https://www.vagrantup.com/docs/synced-folders/nfs.html#root-privilege-requirement
  # for (vagrant) host specific tweaks...
  config.vm.synced_folder '../../', '/home/clear/ClearLinux-packer',
                          type: 'nfs',
                          nfs_udp: false,
                          mount_options: [
                            'rsize=32768',
                            'wsize=32768',
                            'nodiratime',
                            'actimeo=2',
                            'nfsvers=3',
                            'noatime',
                            'nolock',
                            'nocto',
                            'noacl',
                            'intr',
                            'soft',
                            'tcp',
                            'rw'
                          ]
  VMWARE.each do |provider|
    config.vm.provider provider do |vmware|
      vmware.gui = false
      {
        'memsize' => 8192,
        'numvcpus' => 4
      }.each { |k, v| vmware.vmx[k.to_s] = v.to_s }
    end
  end

  config.vm.network :private_network, ip: '192.168.254.2'

  config.vm.provision :bundle_add,
                      bundles: [
                        'clr-installer',
                        'kvm-host',
                        'make'
                      ]

  config.vm.provision 'set nfs sysctl opts',
                      type: 'shell',
                      path: 'sysctl.nfs.sh'
  config.vm.provision 'setup libvirt',
                      type: 'shell',
                      path: '../clearlinux/setup/libvirtd.sh'
  config.vm.provision 'setup packer',
                      type: 'shell',
                      path: '../clearlinux/setup/packer.sh'
  config.vm.provision 'setup vagrant',
                      type: 'shell',
                      path: '../clearlinux/setup/vagrant.sh'
  config.vm.provision :reload
end
