required_plugins = {
  'vagrant-hostsupdater' => {
    'version' => '>= 1.1.1.160'
  },
  'vagrant-reload' => {
    'version' => '>= 0.0.1'
  },
  'vagrant-guests-clearlinux' => {
    'version' => '>= 1.1.0'
  }
}

Vagrant.configure(2) do |config|
  config.vagrant.plugins = required_plugins
  config.vm.define :libvirt
  config.vm.hostname = 'libvirt-host.clearlinux.local'
  config.vm.box = 'AntonioMeireles/clearlinux'
  config.vm.synced_folder '../../', '/home/clear/ClearLinux-packer'
  %w[vmware_fusion vmware_desktop vmware_workstation].each do |provider|
    config.vm.provider provider do |vmware|
      vmware.gui = false
      vmware.vmx[:memsize] = 8192
      vmware.vmx[:numvcpus] = 4
    end
  end
  config.vm.network :private_network, ip: '192.168.254.2'
  config.vm.network :private_network, auto_config: false

  config.vm.provision :bundle_add, bundles: ['kvm-host', 'make']
  config.vm.provision 'setup libvirt', type: 'shell', path: 'setup.sh'

  config.vm.provision :reload
end
